import React from 'react';
import { 
  LayoutDashboard, 
  Package, 
  Wand2, 
  BarChart3, 
  Megaphone, 
  Layers, 
  Settings, 
  Search, 
  Bell, 
  User,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  MoreVertical,
  Zap,
  TrendingUp,
  AlertCircle,
  CheckCircle2,
  X,
  MessageSquare,
  Sparkles,
  Copy,
  RefreshCw,
  Image as ImageIcon,
  Tag,
  Edit,
  Save,
  Globe,
  ShoppingBag,
  Share2,
  Trash2,
  ExternalLink,
  Instagram,
  Mail,
  Type,
  FileText,
  BrainCircuit,
  LayoutTemplate,
  Merge,
  Bot,
  Terminal,
  ShieldCheck,
  Eye,
  Languages,
  Gavel,
  History,
  Hash,
  Filter,
  Database,
  Cloud,
  Download,
  Upload,
  ImagePlus,
  Maximize,
  AlertTriangle,
  ArrowRight
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Products: Package,
  Optimizer: Wand2,
  SEO: Search,
  Marketing: Megaphone,
  Collections: Layers,
  Settings: Settings,
  Search: Search,
  Bell: Bell,
  User: User,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  More: MoreVertical,
  Zap: Zap,
  TrendingUp: TrendingUp,
  Alert: AlertCircle,
  Check: CheckCircle2,
  Close: X,
  Chat: MessageSquare,
  Sparkles: Sparkles,
  Copy: Copy,
  Refresh: RefreshCw,
  Image: ImageIcon,
  Tag: Tag,
  BarChart: BarChart3,
  Edit: Edit,
  Save: Save,
  Globe: Globe,
  ShoppingBag: ShoppingBag,
  Share: Share2,
  Trash: Trash2,
  ExternalLink: ExternalLink,
  Instagram: Instagram,
  Mail: Mail,
  Type: Type,
  Megaphone: Megaphone,
  Layers: Layers,
  FileText: FileText,
  Brain: BrainCircuit,
  Layout: LayoutTemplate,
  Merge: Merge,
  Bot: Bot,
  Terminal: Terminal,
  Shield: ShieldCheck,
  Eye: Eye,
  Languages: Languages,
  Gavel: Gavel,
  History: History,
  Hash: Hash,
  Filter: Filter,
  Database: Database,
  Cloud: Cloud,
  Download: Download,
  Upload: Upload,
  ImagePlus: ImagePlus,
  Maximize: Maximize,
  AlertTriangle: AlertTriangle,
  ArrowRight: ArrowRight
};